class Solution {
    public void setZeroes(int[][] matrix) 
    {
        int n=matrix.length;
        int m=matrix[0].length;
        int i,j,row=0,col=0;
        for(i=0;i<n;i++)
        {
            for(j=0;j<m;j++)
            {
                if(matrix[i][j]==0)
                {
                    if(i==0)
                    {
                        row=1;
                    }
                    if(j==0)
                    {
                        col=1;
                    }
                    matrix[0][j]=0;
                    matrix[i][0]=0;
                }
            }
        }
        for(i=1;i<n;i++)
        {
            if(matrix[i][0]==0)
            {
                for(j=1;j<m;j++)
                {
                    matrix[i][j]=0;
                }
            }
        }
        for(i=1;i<m;i++)
        {
            if(matrix[0][i]==0)
            {
                for(j=1;j<n;j++)
                {
                    matrix[j][i]=0;
                }
            }
        }
        if(matrix[0][0]==0)
        {
            if(col==1)
            {
                for(i=0;i<n;i++)
                {
                    matrix[i][0]=0;
                }
            }
            if(row==1)
            {
                for(j=0;j<m;j++)
                {
                    matrix[0][j]=0;
                }
            }
        }
    }
}